name: EC-NSL Verify Files

on:
  push:
    branches:
      - main

env:
  OPAMROOT: /home/charlie/.opam
  OPAMYES: true
  OPAMJOBS: 2
  ECRJOBS: 1

jobs:
  ec:
    name: Easycrypt Proof Checking
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/easycrypt/ec-test-box:release
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Compile Project
      run: opam exec -- make check
